### ISSUE TITLE
Can't send even with password entered while "Unlock for Staking Only" is active

### ISSUE THREAD

**Issue by TechniumUnlimited** [ignitioncoin/ignitioncoin#10]
Reported by several windows wallet users who had their wallet encrypted and unlocked for staking only - fix currently is to Unlock-> uncheck "for staking only" and then click okay. Then when you send funds, after entering pass it will work.

**Comment by TechniumUnlimited** [comment]
https://github.com/ignitioncoin/ignitioncoin/blob/master/src/qt/sendcoinsdialog.cpp(edited)
https://github.com/ignitioncoin/ignitioncoin/blob/master/src/qt/sendcoinsentry.h(edited)
https://github.com/ignitioncoin/ignitioncoin/blob/master/src/qt/sendcoinsentry.cpp(edited)
https://github.com/ignitioncoin/ignitioncoin/blob/master/src/qt/sendcoinsdialog.h

**Comment by TechniumUnlimited** [comment]
https://github.com/ignitioncoin/ignitioncoin/blob/master/src/qt/sendcoinsdialog.cpp#L302

This line controls encrypted wallet check-

**Comment by fopat** [comment]
I have found a fix for this issue on my fork: https://github.com/fopat/ignitioncoin/commits/jayray-unlock-issue

IMHO the bug is due to 2 things:
- In CWallet::Unlock, when unlocked for staking only, the condition !IsLocked() is triggered because vMasterKey is not empty, which is normal for staking I think => I added the condition !fWalletUnlockStakingOnly
- In askpassphrasedialog.cpp, the checkbox "Unlock for staking only" is set to fWalletUnlockStakingOnly when the dialog is created, even if the checkbox is hidden => I changed the default checkbox value to false in order to do a full unlock when the checkbox is hidden (but the checkbox is still checked by default when going through Settings > Unlock)

Also, I noticed another issue when fixing this: the lock / unlock actions in "Settings" were not updated well when using "Unlock for staking only".
This was caused by the fact that the update relied on the value of fWalletUnlockStakingOnly, but this value was changed after locking / unlocking, and thus after updating the options.
I added a parameter "stakingOnly" in WalletModel::setWalletLocked to control the fWalletUnlockStakingOnly variable when locking / unlocking.


At the moment both fixes are on my fork, on the "jayray-unlock-issue" branch.
You can test or review them, and I will make changes or a pull request if needed :)

**Comment by TechniumUnlimited** [comment]
Closing issue in 24~ hrs if there is no argument against this having been fixed
